import Link from "next/link";
import { notFound } from "next/navigation";
import { getCatalogExercise } from "@/lib/exercises/provider";
import { getPlansWithDays } from "@/lib/workouts/plans";
import { addCatalogExercise } from "../actions";

export default async function ExercisePage({ params, searchParams }: Readonly<{ params: Promise<{ exerciseId: string }>; searchParams: Promise<{ added?: string; error?: string }> }>) {
  const { exerciseId } = await params; const query = await searchParams; const exercise = await getCatalogExercise(exerciseId); if (!exercise) notFound();
  const plans = await getPlansWithDays().catch(() => []);
  return <main className="pb-28 pt-8"><Link className="text-sm text-slate-400" href="/app/exercises">← Exercises</Link><h1 className="mt-5 text-3xl font-black">{exercise.name}</h1><p className="mt-2 font-semibold text-lime-400">{exercise.primaryMuscle}</p><p className="mt-1 text-sm text-slate-400">Secondary: {exercise.secondaryMuscles.join(", ") || "None listed"}<br />Equipment: {exercise.equipment || "Not listed"}</p>
    {query.added ? <p className="mt-5 rounded-xl bg-lime-400/10 p-4 text-lime-300">Exercise added to your plan.</p> : null}{query.error ? <p className="mt-5 rounded-xl bg-red-400/10 p-4 text-red-200">Could not add this exercise.</p> : null}
    {exercise.videoUrl ? <video className="mt-6 aspect-video w-full rounded-2xl bg-black" controls playsInline preload="metadata" src={exercise.videoUrl} /> : <div className="mt-6 flex aspect-video items-center justify-center rounded-2xl bg-slate-900 text-slate-500">No demonstration available</div>}
    <section className="mt-8"><h2 className="text-xl font-bold">How to perform</h2><ol className="mt-4 list-decimal space-y-3 pl-6 text-slate-300">{exercise.instructions.length ? exercise.instructions.map((step) => <li key={step}>{step}</li>) : <li>Provider instructions are not available for this exercise.</li>}</ol></section>
    <details className="mt-8 rounded-2xl border border-slate-800 p-5"><summary className="cursor-pointer font-bold text-lime-400">Add to plan</summary>{plans.length ? <form action={addCatalogExercise} className="mt-5 space-y-4"><input name="exerciseId" type="hidden" value={exercise.id} /><input name="name" type="hidden" value={exercise.name} /><input name="muscleGroup" type="hidden" value={exercise.primaryMuscle} /><input name="equipment" type="hidden" value={exercise.equipment ?? ""} /><label className="block text-sm">Workout day<select className="mt-2 min-h-12 w-full rounded-xl border border-slate-700 bg-slate-950 px-3" name="dayId" required><option value="">Choose a day</option>{plans.map((plan) => <optgroup key={plan.id} label={plan.name}>{plan.days.map((day) => <option key={day.id} value={day.id}>{day.name}</option>)}</optgroup>)}</select></label><div className="grid grid-cols-3 gap-3"><Field name="sets" label="Sets" value="3" /><Field name="targetReps" label="Reps" value="8-12" /><Field name="defaultWeight" label="Weight" value="" /></div><button className="min-h-12 w-full rounded-xl bg-lime-400 font-bold text-slate-950">Add exercise</button></form> : <p className="mt-4 text-slate-400">Create a workout plan before adding exercises.</p>}</details>
  </main>;
}
function Field({ name, label, value }: Readonly<{ name: string; label: string; value: string }>) { return <label className="text-xs text-slate-400">{label}<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 px-2" defaultValue={value} min="0" name={name} required={name !== "defaultWeight"} type={name === "targetReps" ? "text" : "number"} /></label>; }
